version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=XX
      - AWS_ACCESS_KEY_ID=XX
      - AWS_SECRET_ACCESS_KEY=XX
      - AWS_REGION=XX
    depends_on:
      - python
    volumes:
      - ./backend/python_scripts/data_uploaded:/app/python_scripts/data_uploaded
      - onnx_data:/app/python_scripts/data_drawn

  python:
    build: ./backend/python_scripts
    environment:
      - AWS_ACCESS_KEY_ID=XX
      - AWS_SECRET_ACCESS_KEY=XX
      - AWS_REGION=XX
    volumes:
      - ./backend/python_scripts:/app
      - onnx_data:/app/python_scripts/data_drawn
    working_dir: /app
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080

volumes:
  onnx_data:
